import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="relative antialiased min-h-screen grid grid-rows-[auto_1fr_auto] bg-custom">
          <div className="absolute inset-0 bg-white/60  -z-10" />
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
